# Databricks notebook source
# DBTITLE 1,Create Catalog
# MAGIC %sql
# MAGIC --- create a new catalog
# MAGIC CREATE CATALOG IF NOT EXISTS deltasharing

# COMMAND ----------

# MAGIC %sql
# MAGIC SHOW CATALOGS

# COMMAND ----------

# DBTITLE 1,Use Catalog Created
# MAGIC %sql
# MAGIC USE CATALOG deltasharing

# COMMAND ----------

# DBTITLE 1,Grant and Create & Usage Permissions to All Users on the Account
# MAGIC %sql
# MAGIC --- grant create & usage permissions to all users on the account
# MAGIC --- this also works for other account-level groups and individual users
# MAGIC GRANT CREATE,
# MAGIC USAGE on CATALOG deltasharing TO `account users`

# COMMAND ----------

# DBTITLE 1,Create Schema for Tables (AKA Database)
# MAGIC %sql
# MAGIC --- create a new schema under the quick start catalog
# MAGIC CREATE SCHEMA IF NOT EXISTS airlinedata COMMENT "all flight data recieved from partnered airlines and augmented with tripactions platform "

# COMMAND ----------

# DBTITLE 1,Grant Usage to Schema to All Users
# MAGIC %sql
# MAGIC GRANT USAGE ON SCHEMA airlinedata TO `account users`

# COMMAND ----------

# DBTITLE 1,Create Airline Dataframe for Airline Fact Table Creation
# MAGIC %python
# MAGIC initial_df = (spark.read
# MAGIC       .option("header", "true")
# MAGIC       .option("inferSchema", "true")
# MAGIC       .csv("dbfs:/databricks-datasets/airlines/part-00000"))
# MAGIC df_schema = initial_df.schema
# MAGIC 
# MAGIC df = (spark.read
# MAGIC       .schema(df_schema)
# MAGIC       .csv("dbfs:/databricks-datasets/airlines/part-*"))
# MAGIC df.createOrReplaceTempView("airlineDataTemp")

# COMMAND ----------

# DBTITLE 1,Manipulate and Add Segmented Data Column for Exploration of Airline Flights Fact Table
# MAGIC %scala
# MAGIC import org.apache.spark.sql.types._
# MAGIC import sqlContext.implicits._
# MAGIC import org.apache.spark.sql.{SQLContext, SaveMode}
# MAGIC import org.apache.spark.sql.functions._
# MAGIC 
# MAGIC val df = sql("""select * from airlineDataTemp""")
# MAGIC val newColumns = df
# MAGIC     .withColumn(
# MAGIC       "DateString",
# MAGIC       concat(
# MAGIC         col("Year"),
# MAGIC         lit("-"),
# MAGIC         concat(col("Month"), lit("-"), col("DayofMonth"))
# MAGIC       )
# MAGIC     )
# MAGIC .filter($"Year".isNotNull)
# MAGIC val castDate = newColumns.withColumn("Date", date_format($"DateString", "yyyy-MM-dd")).drop($"DateString")
# MAGIC castDate.cache()
# MAGIC castDate.createOrReplaceTempView("airlineDataTemp2")

# COMMAND ----------

# DBTITLE 1,Create Look-Up Code Data for Dimensional Airline Carrier Table
# MAGIC %scala
# MAGIC import org.apache.spark.sql.types._
# MAGIC import sqlContext.implicits._
# MAGIC import org.apache.spark.sql.{SQLContext, SaveMode}
# MAGIC import org.apache.spark.sql.functions._
# MAGIC 
# MAGIC 
# MAGIC val lookupCodes = sc.parallelize(
# MAGIC   Array(
# MAGIC     "04Q,Tradewind Aviation",
# MAGIC "05Q,Comlux Aviation, AG",
# MAGIC "06Q,Master Top Linhas Aereas Ltd.",
# MAGIC "07Q,Flair Airlines Ltd.",
# MAGIC "09Q,Swift Air, LLC d/b/a Eastern Air Lines d/b/a Eastern",
# MAGIC "0BQ,DCA",
# MAGIC "0CQ,ACM AIR CHARTER GmbH",
# MAGIC "0FQ,Maine Aviation Aircraft Charter, LLC",
# MAGIC "0GQ,Inter Island Airways, d/b/a Inter Island Air",
# MAGIC "0HQ,Polar Airlines de Mexico d/b/a Nova Air",
# MAGIC "0J,JetClub AG",
# MAGIC "0JQ,Vision Airlines",
# MAGIC "0LQ,Metropix UK, LLP.",
# MAGIC "0MQ,Multi-Aero, Inc. d/b/a Air Choice One",
# MAGIC "0OQ,Open Skies",
# MAGIC "0Q,Flying Service N.V.",
# MAGIC "0QQ,TAG Aviation (UK) Ltd.",
# MAGIC "0RQ,TAG Aviation Espana S.L.",
# MAGIC "0TQ,Corporatejets, XXI",
# MAGIC "0UQ,Comlux Malta, Ltd.",
# MAGIC "0VQ,Ocean Sky (UK) Limited",
# MAGIC "0WQ,Avjet Corporation",
# MAGIC "0YQ,Comlux Malta Ltd.",
# MAGIC "10Q,Swiss Air Ambulance",
# MAGIC "12Q,Unijet",
# MAGIC "13Q,Chartright Air Inc.",
# MAGIC "14Q,London Air Services Limited",
# MAGIC "15Q,Air Alsie A/S",
# MAGIC "17Q,Albinati Aeronautics SA",
# MAGIC "1AQ,Via Airlines d/b/a Charter Air Transport",
# MAGIC "1BQ,Eastern Airlines f/k/a Dynamic Airways, LLC",
# MAGIC "1DQ,Island Airlines LLC",
# MAGIC "1EQ,KaiserAir, Inc.",
# MAGIC "1FQ,Alsek Air",
# MAGIC "1HQ,International Jet Management GmbH",
# MAGIC "1I,Sky Trek International Airlines",
# MAGIC "1IQ,Jet link AG",
# MAGIC "1JQ,Exec Direct Aviation Services Limited",
# MAGIC "1LQ,Bertelsmann Aviation GmbH",
# MAGIC "1MQ,Twin Cities Air Service LLC",
# MAGIC "1NQ,JSC The 224th Flight Unit State Airlines",
# MAGIC "1PQ,Makani Kai Air Charters",
# MAGIC "1QQ,City Wings Inc dba Seaflight",
# MAGIC "1RQ,Sun Air Express LLC dba Sun Air International",
# MAGIC "1SQ,Star Marianas Air Inc.",
# MAGIC "1TQ,Rhoades Aviation dba Transair",
# MAGIC "1UQ,Gainjet Aviation SA",
# MAGIC "1WQ,Ultimate JetCharters LLC dba Ultimate Air Shuttle",
# MAGIC "1XQ,Dassault Falcon Service",
# MAGIC "1YQ,Air Charter, Inc d/b/a Air Flamenco",
# MAGIC "1ZQ,Comlux Aruba NV",
# MAGIC "20Q,Orange Air",
# MAGIC "22Q,Gem Air LLC",
# MAGIC "23Q,Songbird Airways Inc.",
# MAGIC "24Q,Blue Jet SP Z o o",
# MAGIC "25Q,Mjet GmbH",
# MAGIC "26Q,Albinati aviation Limited",
# MAGIC "27Q,Jet Aviation Flight Services, Inc.",
# MAGIC "28Q,Menagerie Enterprises Inc d/b/a Monarch Air",
# MAGIC "29Q,Erickson Helicopters",
# MAGIC "2AQ,ABS JETS A.S",
# MAGIC "2BQ,Air Medical Ltd.",
# MAGIC "2E,Smokey Bay Air Inc.",
# MAGIC "2EQ,J&M Alaska Air Tours, Inc. d/b/a Alaska Air Transit",
# MAGIC "2F,Frontier Flying Service",
# MAGIC "2GQ,Cavok Air LLC",
# MAGIC "2HQ,Elite Airways LLC",
# MAGIC "2JQ,Delux Public Charter LLC",
# MAGIC "2K,Aerolineas Galapagos S A Aerogal",
# MAGIC "2KQ,Longtail Aviation Ltd.",
# MAGIC "2LQ,Tropic Ocean Airways LLC",
# MAGIC "2M,Midway Express Airlines",
# MAGIC "2NQ,LIMA NY Corp d/b/a Fly The Whale d/b/a Tailwind",
# MAGIC "2O,Island Air Service",
# MAGIC "2OQ,Talofa Airways Limited",
# MAGIC "2P,Air Philippines Corp d/b/a Airphil Express, Philippines Airlines",
# MAGIC "2PQ,21 Air LLC",
# MAGIC "2R,Regal Air",
# MAGIC "2RQ,Luxaviation S A",
# MAGIC "2T,Canada 3000 Airlines Ltd.",
# MAGIC "2TQ,Trans Northern Airways d/b/a Air Unlimited Charter Services",
# MAGIC "2U,Valley Air Express Inc.",
# MAGIC "2UQ,Svenskt Industriflyg AB",
# MAGIC "30Q,Public Charters, Inc. d/b/a North Country Sky d/b/a Regional Sky d/b/a Texas Sky",
# MAGIC "34Q,Polaris Aviation Solutions, LLC",
# MAGIC "35Q,Aztec Worldwide Airlines, Inc. d/b/a Aztec Airways",
# MAGIC "36Q,Air Hamburg Luftverkehrsgesellschaft mbH",
# MAGIC "37,Zeal 320",
# MAGIC "37Q,Hillwood Airways, LLC f/k/a ATX Air Services, LLC",
# MAGIC "38Q,Key Lime Air Corporation",
# MAGIC "3AQ,Maritime Helicopters, Inc.",
# MAGIC "3BQ,Nealco Air Charter Services, Inc. d/b/a Watermakers Air",
# MAGIC "3C,Regions Air, Inc.",
# MAGIC "3CQ,Andrew Airways, Inc.",
# MAGIC "3DQ,Rectrix Aviation, Inc.",
# MAGIC "3EQ,Scott Aviation, LLC d/b/a Silver Air",
# MAGIC "3F,Pacific Airways, Inc.",
# MAGIC "3FQ,Western Air Charter, Inc. d/b/a Jet Edge",
# MAGIC "3M,Silver Airways",
# MAGIC "3S,AeroLogic GmbH",
# MAGIC "3SD,Compagnie Aerienne Inter Regionale Express dba Air Antilles Express & Air Guyane",
# MAGIC "3U,Sichuan Airlines Co Ltd.",
# MAGIC "4B,Boutique Air",
# MAGIC "4B (1),Olson Air Service",
# MAGIC "4C,Aerovias de Intergracian Regional",
# MAGIC "4E,British Airtours Limited",
# MAGIC "4H,Belize Trans Air",
# MAGIC "4M,LAN Argentina",
# MAGIC "4M (1),Lan Dominica",
# MAGIC "4N,Air North",
# MAGIC "4O,ABC Aerolineas SA de CV dba Interjet",
# MAGIC "4R,Regent Air Corporation",
# MAGIC "4S,Sol Air (Aero Hunduras)",
# MAGIC "4S (1),Conner Air Lines Inc.",
# MAGIC "4T,Belair Airlines Ltd.",
# MAGIC "4W,Warbelow",
# MAGIC "4Y,Yute Air Aka Flight Alaska",
# MAGIC "5B,Bellair Inc.",
# MAGIC "5C,C.A.L Cargo Airlines",
# MAGIC "5D,Aerolitoral",
# MAGIC "5F,Arctic Circle Air Service",
# MAGIC "5G,Skyservice Airlines, Inc.",
# MAGIC "5G (1),Queen Air",
# MAGIC "5J,Cebu Air Inc d/b/a Cebu Pacific Air",
# MAGIC "5J (1),Private Jet Expeditions",
# MAGIC "5L,Aerosur",
# MAGIC "5V,Tatonduk Outfitters Limited d/b/a Everts Air Alaska and Everts Air Cargo",
# MAGIC "5X,United Parcel Service",
# MAGIC "5Y,Atlas Air Inc.",
# MAGIC "6A,Aviacsa Airlines",
# MAGIC "6B,TUIfly Nordic A.B.",
# MAGIC "6C,Cape Smythe Air Service",
# MAGIC "6F,Laker Airways Inc.",
# MAGIC "6H,Israir Airlines",
# MAGIC "6P,Pacific East Air Inc.",
# MAGIC "6R,Aerounion Aerotransporte de Carga Union SA de CV",
# MAGIC "6U,Air Ukraine",
# MAGIC "6Y,Nicaraguense De Aviacion Sa",
# MAGIC "7B,Krasair",
# MAGIC "7C,Jeju Air Co Ltd.",
# MAGIC "7F,First Air",
# MAGIC "7G,MK Airlines Ltd.",
# MAGIC "7G (1),Bellair Inc. (1)",
# MAGIC "7H,Era Aviation",
# MAGIC "7I,Insel Air International B V",
# MAGIC "7L,Silk Way West Airlines",
# MAGIC "7M,Aeromonterrey S.A.",
# MAGIC "7N,Inland Aviation Services",
# MAGIC "7P,Apa International Air S.A.",
# MAGIC "7Q,Pan American World Airways Dominicana",
# MAGIC "7S,Ryan Air f/k/a Arctic Transportation",
# MAGIC "7S (1),Skystar International Inc.",
# MAGIC "7Z,Lb Limited",
# MAGIC "8C,Air Transport International",
# MAGIC "8D,Dynamic Aviation, Inc. d/b/a Beacon",
# MAGIC "8E,Bering Air Inc.",
# MAGIC "8F,Wilburs Inc.",
# MAGIC "8I,Inselair Aruba NV",
# MAGIC "8J,Jetall Airways",
# MAGIC "8L,Servicio Aereo Leo Lopez",
# MAGIC "8N,Flagship Airlines Inc.",
# MAGIC "8Q,Baker Aviation Inc.",
# MAGIC "8R,Edelweiss Air Ag",
# MAGIC "8V,Wright Air Service",
# MAGIC "9E,Endeavor Air Inc.",
# MAGIC "9J,Pacific Island Aviation",
# MAGIC "9K,Cape Air",
# MAGIC "9L,Colgan Air",
# MAGIC "9M,Central Mountain Air",
# MAGIC "9N,ANA & JP Express Co. Ltd.",
# MAGIC "9R,Flagship Express Services",
# MAGIC "9S,Southern Air Inc.",
# MAGIC "9T,TravelspanGT, Inc. S.A.",
# MAGIC "9V,Avior Airlines, C.A.",
# MAGIC "9W,Jet Airways (India) Limited",
# MAGIC "A0,Elysair d/b/a L'Avion",
# MAGIC "A2,Cielos De Peru",
# MAGIC "A4,Southern Wind Airlines",
# MAGIC "A7,Air Comet S.A.",
# MAGIC "A7 (1),Air 21",
# MAGIC "AA,American Airlines Inc.",
# MAGIC "AAA,Associated Aviation Act.",
# MAGIC "AAB,Abelag Aviation AG",
# MAGIC "AAB (1),Antilles Air Boats Inc.",
# MAGIC "AAE,AAA Airlines",
# MAGIC "AAI,Audi Air Inc.",
# MAGIC "AAL,Argosy Air Lines Inc.",
# MAGIC "AAP,Armstrong Air Service Inc.",
# MAGIC "AAQ,Advance Air Charters",
# MAGIC "AAR,Altair Airlines Inc.",
# MAGIC "AAT,Air Sunshine Inc.",
# MAGIC "AAV,Alpine Air",
# MAGIC "AAZ,Alaska Aeronautical Indust.",
# MAGIC "AB,Air Berlin PLC and CO",
# MAGIC "ABH,Air Bahia",
# MAGIC "ABI,Airbama Incorporated",
# MAGIC "ABO,Aeronaves Boringuena Inc.",
# MAGIC "ABX,ABX Air Inc",
# MAGIC "AC,Air Canada",
# MAGIC "ACA,Alaska Central Airways Inc.",
# MAGIC "ACD,Academy Airlines",
# MAGIC "ACG,Air Cargo Express Inc.",
# MAGIC "ACH,Island Airlines Hawaii Inc.",
# MAGIC "ACI,AAA-Action Air Carrier Inc.",
# MAGIC "ACJ,Atlantic Coast Jet Inc.",
# MAGIC "ACK,Air Central Inc.",
# MAGIC "ACL,Check-Air Inc.",
# MAGIC "ACN,Alliance Airlines",
# MAGIC "ACO,Air Cargo Enterprises Inc.",
# MAGIC "ACP,Air Chaparral Inc.",
# MAGIC "ACQ,Aeronautica De Cancun",
# MAGIC "ACS,Alamo Commuter Airlines",
# MAGIC "ACT,Air Central Inc. (1)",
# MAGIC "ACW,Transwest Air Express",
# MAGIC "AD,Azul Linhas Aereas Brazileiras S A",
# MAGIC "AD (1),Avia Leasing Company",
# MAGIC "ADB,Antonov Company",
# MAGIC "ADQ,Aeronaves Del Peru",
# MAGIC "ADR,Adirondack Airlines",
# MAGIC "ADV,Advantage Airlines",
# MAGIC "AE,Air Europe Limited",
# MAGIC "AEC,Astec Air East Inc.",
# MAGIC "AED,Air East Of Delaware Inc.",
# MAGIC "AEF,Aero Freight",
# MAGIC "AEO,Aero Coach",
# MAGIC "AEQ,Air Caravane Inc.",
# MAGIC "AEX,Air Excursions LLC (1)",
# MAGIC "AF,Compagnie Natl Air France",
# MAGIC "AFA,American Flag Airlines Inc.",
# MAGIC "AFE,Air Florida Express",
# MAGIC "AFG,American Flight Group",
# MAGIC "AFQ,Aero B Venezuela C.A.",
# MAGIC "AFS,Arcata Flying Service",
# MAGIC "AG,Arubaanse Luchtvaart Maatschappij NV dba Aruba Airlines",
# MAGIC "AGA,Air Cargo America Inc.",
# MAGIC "AGQ,Argo S. A.",
# MAGIC "AHA,Air Alpha",
# MAGIC "AHC,Air Hawaii",
# MAGIC "AHQ,Air National",
# MAGIC "AI,National Aviation Company of India Limited d/b/a Air India",
# MAGIC "AIA,All Island Air",
# MAGIC "AIC,Air Caribbean",
# MAGIC "AIE,Air Express Inc.",
# MAGIC "AIG,Airgo Inc.",
# MAGIC "AIK,Air Ketchum Idaho Inc.",
# MAGIC "AIM,Air Mont. Inc.",
# MAGIC "AIN,Air Indiana",
# MAGIC "AIQ,Norontair",
# MAGIC "AIT,Airways International",
# MAGIC "AIY,Alliance Air",
# MAGIC "AJ,Air Micronesia Inc.",
# MAGIC "AJQ,Aerodynamics Inc. d/b/a SkyValue d/b/a SkyValue Airways",
# MAGIC "AKQ,Airmark Airlines Inc.",
# MAGIC "AL,Skyway Airlines",
# MAGIC "ALD,Allied Airlines",
# MAGIC "ALE,Air-Lift Associates Inc.",
# MAGIC "ALI,Brandt Air",
# MAGIC "ALK,Air Link Airways",
# MAGIC "ALL,All Seasons Air Pacific",
# MAGIC "ALQ,Alberta Northern Airlines",
# MAGIC "ALS,Air L.A.",
# MAGIC "ALT,Altus Airlines",
# MAGIC "ALU,Aleutian Air",
# MAGIC "ALX,Atlanta Express",
# MAGIC "AM,Aeromexico",
# MAGIC "AMA,North American Airlines Inc.",
# MAGIC "AME,Americair Inc.",
# MAGIC "AMI,American Inter-Island Inc.",
# MAGIC "AMQ,Ameristar Air Cargo",
# MAGIC "AMR,AvAir",
# MAGIC "AMT,American Air Transport",
# MAGIC "AN,ADVANCED AIR, LLC",
# MAGIC "ANB,Air Nebraska Inc.",
# MAGIC "ANC,Atlantic Air",
# MAGIC "AND,Southcentral Air Inc.",
# MAGIC "ANI,Dash Air Corporation",
# MAGIC "ANM,Airways Of New Mexico Inc.",
# MAGIC "ANO,Metro Air Northeast Vermont",
# MAGIC "ANT,Air North/Nenana",
# MAGIC "AO,Aviacion Y Comercio S.A.",
# MAGIC "AOI,Trans New York",
# MAGIC "AON,Action Airlines",
# MAGIC "AOQ,Aerovias S.A.",
# MAGIC "AOR,Air New Orleans",
# MAGIC "APE,Air Cape",
# MAGIC "APH,Alpha Air",
# MAGIC "API,Arizona Pacific Inc.",
# MAGIC "APL,Appalachian Flying Service",
# MAGIC "APN,Aspen Airways Inc.",
# MAGIC "APQ,Alas De Transporte International",
# MAGIC "APS,Air Spirit Inc.",
# MAGIC "APY,Air Polynesia Inc.",
# MAGIC "AQ,Aloha Airlines Inc.",
# MAGIC "AQQ,Air Charter (Safa)",
# MAGIC "AR,Aerolineas Argentinas",
# MAGIC "ARA,Air Resorts Airlines",
# MAGIC "ARB,Air Caribe International",
# MAGIC "ARD,Airlift International",
# MAGIC "ARI,Arizona Aero Corp.",
# MAGIC "ARM,Airmarc Airlines Inc.",
# MAGIC "ARN,Arnold Aviation",
# MAGIC "ARO,Air Oregon",
# MAGIC "ARP,Airspur Helicopters Inc.",
# MAGIC "ARQ,Aerovias Colombianas Arca",
# MAGIC "ARR,Arrowhead Airways Inc.",
# MAGIC "ARS,Air Sedona",
# MAGIC "ARZ,Arizona Airways",
# MAGIC "AS,Alaska Airlines Inc.",
# MAGIC "ASC,Air South Inc.",
# MAGIC "ASD,Amistad Airlines",
# MAGIC "ASH,Air South",
# MAGIC "ASI,Alpine Air Services Inc.",
# MAGIC "ASN,Air Casino",
# MAGIC "ASP,Asap Air Inc.",
# MAGIC "ASQ,Aerosur (1)",
# MAGIC "ASR,Astor Air",
# MAGIC "AST,Astro Airways",
# MAGIC "ASU,Air South (1)",
# MAGIC "ASW,Sunrise Airlines Inc.",
# MAGIC "AT,Royal Air Maroc",
# MAGIC "ATH,Air Southeast",
# MAGIC "ATN,Air Atlantic Airlines Inc.",
# MAGIC "ATO,Pacific National Airways",
# MAGIC "ATQ,Aero Tranportes Panamenos",
# MAGIC "ATS,Atlantis Airlines Inc.",
# MAGIC "ATT,Aerotransit Inc.",
# MAGIC "ATX,Air Carolina",
# MAGIC "AUX,Austin Express Inc.",
# MAGIC "AV,Aerovias Nacl De Colombia",
# MAGIC "AVA,Air Vectors Airways",
# MAGIC "AVC,Av Center Inc.",
# MAGIC "AVG,Airvantage",
# MAGIC "AVI,Aero Virgin Islands Corp.",
# MAGIC "AVL,Aviation Sales",
# MAGIC "AVQ,Aero Laguna S.A. De C.V.",
# MAGIC "AVR,Air Vermont Inc.",
# MAGIC "AVS,Aviation Services",
# MAGIC "AVZ,Southern Jersey Airways",
# MAGIC "AWA,Air West Airlines",
# MAGIC "AWQ,Aermediterranea S.P.A.",
# MAGIC "AX,Trans States Airlines",
# MAGIC "AXQ,Aeron International Airlines Inc.",
# MAGIC "AY,Finnair Oy",
# MAGIC "AYQ,Aerodan S.A. De C.V.",
# MAGIC "AZ,Compagnia Aerea Italiana",
# MAGIC "AZP,Arizona Pacific Airways",
# MAGIC "AZQ,Anglo Airlines Ltd.",
# MAGIC "B0,Dreamjet SAS Dba La Compagnie",
# MAGIC "B6,JetBlue Airways",
# MAGIC "BA,British Airways Plc",
# MAGIC "BAA,Aero International Airlines",
# MAGIC "BAC,Business Aircraft Corp.",
# MAGIC "BAH,Brennan & Hargreaves Inc.",
# MAGIC "BAK,Bankair Inc.",
# MAGIC "BAN,Bangor International Air",
# MAGIC "BAQ,Aero Rentas De Coahuila S.A. De C.V.",
# MAGIC "BAR,Bard-Air Corp.",
# MAGIC "BAT,West Penn Commuter",
# MAGIC "BAY,Burlington Aeroplane Co.",
# MAGIC "BBQ,Balair Ag",
# MAGIC "BC,Skymark Airlines Inc.",
# MAGIC "BCA,Baja Cortez Airlines",
# MAGIC "BCQ,Bradley Air Services Ltd.",
# MAGIC "BD,British Midland Airways Ltd.",
# MAGIC "BDE,Jet Express",
# MAGIC "BDQ,Aerotaxis De Aguascalientes S.A. De C.V.",
# MAGIC "BE,Braniff International Airlines Inc.",
# MAGIC "BEA,Business Express Airlines",
# MAGIC "BEN,Bennington Aviation Inc.",
# MAGIC "BEQ,Air Belgium",
# MAGIC "BES,Aeroservices Executive",
# MAGIC "BEY,Beyer Aviation",
# MAGIC "BF,Markair Inc.",
# MAGIC "BFG,Million Air",
# MAGIC "BFQ,Buffalo Airways Inc.",
# MAGIC "BG,Biman Bangladesh Airlines",
# MAGIC "BGQ,Airbus Transport Internat'l",
# MAGIC "BHK,Blackhawk Airways Inc.",
# MAGIC "BHO,Bighorn Airways Inc.",
# MAGIC "BHQ,Turks Air Ltd. (1)",
# MAGIC "BIA,Big Island Air",
# MAGIC "BIQ,Servicios Aeronauticos Z S.A. De C.V.",
# MAGIC "BIR,Birchwood Air Service",
# MAGIC "BJQ,Taxirey S.A. De C.V.",
# MAGIC "BLQ,Air Bvi Limited",
# MAGIC "BM,Belize Air International Ltd.",
# MAGIC "BMT,Bremerton Aviation Inc.",
# MAGIC "BN,Britannia Airways GmbH",
# MAGIC "BN (1),Braniff Inc.",
# MAGIC "BNQ,NetJets Large Aircraft Company L.L.C.",
# MAGIC "BOA,Boise Air Service",
# MAGIC "BOI,Bo-S-Aire Airlines Inc.",
# MAGIC "BOQ,Transp. Aereos Bolivianos",
# MAGIC "BQ,Aeromar C. Por A.",
# MAGIC "BR,Eva Airways Corporation",
# MAGIC "BR (1),Cal Air International Ltd.",
# MAGIC "BRK,Barken International",
# MAGIC "BRO,Brower Airways Inc.",
# MAGIC "BRW,Barrow Air",
# MAGIC "BTQ,Brasair Transportes Aereos",
# MAGIC "BUH,Business Helicopters",
# MAGIC "BUQ,Wrangler Aviation Inc.",
# MAGIC "BUQ (1),Blue Bell Inc.",
# MAGIC "BUR,Burlington Airways Inc.",
# MAGIC "BW,Caribbean Airlines Limited",
# MAGIC "BX,Air Busan",
# MAGIC "BXQ,Spantax S. A.",
# MAGIC "BY,Britannia Airways Ltd.",
# MAGIC "BYA,Bay Air",
# MAGIC "BZQ,Abaco Air, Ltd.",
# MAGIC "C5,Commutair Aka Champlain Enterprises, Inc.",
# MAGIC "C6,Canjet Airlines",
# MAGIC "C8,Cargolux Italia SpA",
# MAGIC "C8 (1),Chicago Express Airlines",
# MAGIC "CA,Air China",
# MAGIC "CAC,Coleman Air Transport",
# MAGIC "CAF,California Seaboard",
# MAGIC "CAI,Crawford Aviation Inc.",
# MAGIC "CAM,C & M Airlines",
# MAGIC "CAP,Metro Air Northeast N Y",
# MAGIC "CAQ,Challenge Air Luftverkehrs GmbH",
# MAGIC "CAT,Catalina Airlines Inc.",
# MAGIC "CAV,Air Virginia",
# MAGIC "CAZ,CAT Aviation",
# MAGIC "CB,Air One Inc.",
# MAGIC "CBA,Carriba Air Inc.",
# MAGIC "CC,Air Atlanta Icelandic",
# MAGIC "CC (1),Air Atlanta Inc.",
# MAGIC "CCA,Cityhop",
# MAGIC "CCO,Chester County Aviation",
# MAGIC "CDQ,Kitty Hawk International",
# MAGIC "CEN,Cen-Tex Airlines Inc.",
# MAGIC "CEQ,All Canada Express",
# MAGIC "CET,Century Airlines (Cal)",
# MAGIC "CF,Compan. De Aviacion Faucett",
# MAGIC "CGA,Chicago Airlines",
# MAGIC "CGL,Viking International Airlines Inc.",
# MAGIC "CGO,Chicago Air Taxi",
# MAGIC "CH,Bemidji Airlines",
# MAGIC "CHD,Chandler Flyer",
# MAGIC "CHE,Charter Airlines",
# MAGIC "CHF,Hammonds Commuter Air Serv.",
# MAGIC "CHI,Chitina Air Service",
# MAGIC "CHL,Channel Flying Inc.",
# MAGIC "CHO,Choi Aviation Inc.",
# MAGIC "CHS,Christman Air System",
# MAGIC "CHT,Charter One",
# MAGIC "CI,China Airlines Ltd.",
# MAGIC "CIQ,A/S Conair",
# MAGIC "CIS,Cal Sierra Airlines",
# MAGIC "CJ,Colgan Airways Inc.",
# MAGIC "CK,China Cargo Airline",
# MAGIC "CKI,Inlet Airlines",
# MAGIC "CL,Capitol International Inc.",
# MAGIC "CLB,Columbia Pacific Airlines",
# MAGIC "CLD,Hawaii Pacific Helicopters",
# MAGIC "CLF,California Air Shuttle",
# MAGIC "CLQ,Aero Transcolombiana",
# MAGIC "CM,Compania Panamena (Copa)",
# MAGIC "CMB,Combs Airways Inc.",
# MAGIC "CMD,Command Airways Inc.",
# MAGIC "CMQ,Servicio De Carga Aerea Sa",
# MAGIC "CMR,Commuter Airlines (Ca)",
# MAGIC "CNN,Centennial Airlines",
# MAGIC "CO,Continental Air Lines Inc.",
# MAGIC "COB,Cotton Belt Aviation Inc.",
# MAGIC "COC,Cochise Airlines Inc.",
# MAGIC "COK,Coker Aviation Inc.",
# MAGIC "COL,Presidential Express",
# MAGIC "COM,Commutair",
# MAGIC "COR,Coral Air Inc.",
# MAGIC "COS,Cosmopolitan Comm. Airline",
# MAGIC "COT,Southeastern Commuter",
# MAGIC "COU,Courtesy Air Service Inc.",
# MAGIC "CP,Compass Airlines",
# MAGIC "CP (1),Canadian Airlines International Ltd.",
# MAGIC "CPA,Capitol Air Lines",
# MAGIC "CPC,Coastal Plains Commuter Inc.",
# MAGIC "CPQ,Capitol Air Express Inc.",
# MAGIC "CPT,Capitol Air",
# MAGIC "CQI,Conquest Airline Corp.",
# MAGIC "CRA,Commuter Airlines",
# MAGIC "CRB,Caribair",
# MAGIC "CRE,Caribbean Express Inc.",
# MAGIC "CRH,Cresent Medivac",
# MAGIC "CRN,Crown Aviaiton Inc.",
# MAGIC "CRO,Crown Airways Inc.",
# MAGIC "CRP,Corporate Air",
# MAGIC "CRT,Crested Butte Air Service",
# MAGIC "CRV,Acropolis Aviation Ltd.",
# MAGIC "CS,Continental Micronesia",
# MAGIC "CSA,Casino Airlines",
# MAGIC "CSK,Catskill Airways Inc.",
# MAGIC "CSL,Central States Air Lines",
# MAGIC "CSM,Chisum Flying Service",
# MAGIC "CSN,Casino Airlines (1)",
# MAGIC "CSQ,Celtic Tech Jet Ltd.",
# MAGIC "CTA,Century Airlines",
# MAGIC "CTH,Cothron Aviation",
# MAGIC "CTL,Coastal Air Transport",
# MAGIC "CTQ,Custom Air Transport",
# MAGIC "CTR,Chartair",
# MAGIC "CUQ,Caicos Caribbean Airways",
# MAGIC "CUS,Custom Air Service",
# MAGIC "CV,Cargolux Airlines International S.A",
# MAGIC "CVA,Catalina-Vegas Airlines",
# MAGIC "CVQ,Caraven S.A.",
# MAGIC "CW,Air Marshall Islands Inc.",
# MAGIC "CWQ,Canadian Aviation Express",
# MAGIC "CX,Cathay Pacific Airways Ltd.",
# MAGIC "CYQ,Corse Air International",
# MAGIC "CZ,China Southern Airlines",
# MAGIC "CZ (1),Cascade Airways Inc.",
# MAGIC "CZQ,Aviation Concepts",
# MAGIC "D7,Air Asia X Berhad dba Airasia X",
# MAGIC "D8,Norwegian Air International Ltd.",
# MAGIC "DA,Dan Air Services",
# MAGIC "DAN,Danbury Airlines",
# MAGIC "DAU,Dauphin Island Airways",
# MAGIC "DC,Caribbean Air Cargo Co Ltd.",
# MAGIC "DE,Condor Flugdienst",
# MAGIC "DEA,Downeast Airlines Inc.",
# MAGIC "DEC,Decatur Aviation",
# MAGIC "DFS,Downeast Flying Service",
# MAGIC "DH,Independence Air",
# MAGIC "DH (1),Discovery Airways Inc.",
# MAGIC "DHL,DHL Airlines Inc.",
# MAGIC "DHQ,DHL Aero Expresso",
# MAGIC "DI,Norwegian Air UK Limited",
# MAGIC "DIA,Drummond Island Air",
# MAGIC "DIC,Dickman Aviation Services",
# MAGIC "DIR,Northern Star",
# MAGIC "DL,Delta Air Lines Inc.",
# MAGIC "DM,Maersk Air I/S",
# MAGIC "DO,Compania Dominicana De Avia",
# MAGIC "DOL,Dolphin Airways Inc.",
# MAGIC "DOQ,Aerolineas Dominicanas S A",
# MAGIC "DPA,Desert Pacific Airways",
# MAGIC "DPI,Desert Pacific Airlines Inc.",
# MAGIC "DQQ,Caribwest Airways Ltd.",
# MAGIC "DSA,Desert Sun Airlines",
# MAGIC "DST,Desert Airlines",
# MAGIC "DUL,Dulles Express",
# MAGIC "DUZ,Summit Airlines Inc.",
# MAGIC "DVO,Devoe Airlines",
# MAGIC "DWN,Dawn Air",
# MAGIC "DXA,Dolphin Express",
# MAGIC "DY,Norwegian Air Shuttle ASA",
# MAGIC "E0,EOS Airlines, Inc.",
# MAGIC "E7,Estafeta Carga Aereas",
# MAGIC "E72,European Aviation Air Charter",
# MAGIC "E8,USAfrica Airways Inc.",
# MAGIC "E9,Evelop Airlines SL",
# MAGIC "E9 (1),Boston-Maine Airways",
# MAGIC "EA,Eastern Air Lines Inc.",
# MAGIC "EAI,Executive Aviation Inc.",
# MAGIC "EAQ,Executive Airlines, SL",
# MAGIC "EAS,Eastern Caribbean Airways",
# MAGIC "EAT,Eastman Airways Inc.",
# MAGIC "EBQ,Execaire Aviation Ltd.",
# MAGIC "ECA,Eagle Airlines (1)",
# MAGIC "ECI,Eastern Carolina Aviation",
# MAGIC "ECL,Eclipse Airlines",
# MAGIC "ECQ,Trans American Charter",
# MAGIC "ECR,East Coast Airways",
# MAGIC "ED,Andes",
# MAGIC "EDE,Ede Aire",
# MAGIC "EE,Eastern Airlines Group Inc.",
# MAGIC "EET,Exec Express II",
# MAGIC "EEX,Exec Express",
# MAGIC "EEZ,Eagle Aviation Inc.",
# MAGIC "EFA,Executive Four Winds",
# MAGIC "EFQ,Trans Europ. Airways France",
# MAGIC "EGA,Eagle Airline",
# MAGIC "EGJ,Eagle Jet Charter",
# MAGIC "EGL,Eagle Commuter Airlines Inc.",
# MAGIC "EH,Saeta Airlines",
# MAGIC "EHA,East Hampton Aire Inc.",
# MAGIC "EI,Aer Lingus Plc",
# MAGIC "EIA,East. Indiana Aviation Sale",
# MAGIC "EJQ,Aeroejecutivos C.A.",
# MAGIC "EK,Emirates",
# MAGIC "EKA,Air Pacific Inc.",
# MAGIC "ELL,Ellis Air Taxi Inc.",
# MAGIC "EM,Empire Airlines Inc.",
# MAGIC "EMA,Emerald Airlines",
# MAGIC "EME,Metro Express",
# MAGIC "EMP,Empire Airlines Inc. (2)",
# MAGIC "ENT,Enterprise Airlines Inc.",
# MAGIC "EOQ,Aeroservicios Ecuatorianos",
# MAGIC "EP,All Star Airlines Inc.",
# MAGIC "EQ,Tame Linea Aerea del Ecuador Tme EP",
# MAGIC "ER,Astar USA, LLC",
# MAGIC "ERI,Erie Airways Inc.",
# MAGIC "ERO,Empire Aero Service",
# MAGIC "ERQ,Aero Trades (Western) Ltd.",
# MAGIC "ESQ,Seagreen Air Transport",
# MAGIC "ET,Ethiopian Airlines",
# MAGIC "EU,Ecuatoriana De Aviacion",
# MAGIC "EUQ,Air Atlanta Europe",
# MAGIC "EV,ExpressJet Airlines Inc.",
# MAGIC "EVA,Evanston Aviation",
# MAGIC "EW,Eurowings GmbH",
# MAGIC "EWA,Rio Grande Air",
# MAGIC "EXA,Columbia Pacific Airlines (1)",
# MAGIC "EXC,Hapag-Lloyd Executive GmbH",
# MAGIC "EXC (1),Executive Charter",
# MAGIC "EXP,Express Airlines II",
# MAGIC "EXQ,Export Air Del Peru S.A.",
# MAGIC "EXR,Executive Transport",
# MAGIC "EY,Etihad Airways",
# MAGIC "EZ,Evergreen International Inc.",
# MAGIC "F2,Omega Air Holdings d/b/a Focus Air",
# MAGIC "F8,Freedom Airlines d/b/a HP Expr",
# MAGIC "F9,Frontier Airlines Inc.",
# MAGIC "FAA,Falwell Aviation Inc.",
# MAGIC "FAC,Falcon Airways Inc.",
# MAGIC "FAQ,Fast Air Carrier Ltd. (1)",
# MAGIC "FAR,Federal Armored Service Inc.",
# MAGIC "FB,Translift Airways Limited",
# MAGIC "FBI,Young Flying Service",
# MAGIC "FC,Fast Colombia SAS d/b/a Viva Colombia",
# MAGIC "FCA,Southern Airlines Inc.",
# MAGIC "FCQ,Falcon Air Express",
# MAGIC "FD,Air Puerto Rico Airlines",
# MAGIC "FDA,Florida Airlines Inc.",
# MAGIC "FDM,Freedom Airlines Inc.",
# MAGIC "FDQ,Great American Airways",
# MAGIC "FE,Primaris Airlines Inc.",
# MAGIC "FF,Tower Air Inc.",
# MAGIC "FFQ,Five Star Airlines",
# MAGIC "FH,Frontier Horizon Inc.",
# MAGIC "FI,Icelandair",
# MAGIC "FJ,Air Pacific Ltd.",
# MAGIC "FJ (1),Air Pacific Ltd. (1)",
# MAGIC "FL,AirTran Airways Corporation",
# MAGIC "FL (1),Frontier Airlines Inc. (1)",
# MAGIC "FLA,Florida Air",
# MAGIC "FLM,Flamenco Airways Inc.",
# MAGIC "FLR,Flirite Inc.",
# MAGIC "FNQ,Fine Airlines Inc.",
# MAGIC "FOR,Ford-Aire Inc.",
# MAGIC "FOS,Foster Aviation",
# MAGIC "FP,TAG Aviation S.A.",
# MAGIC "FQ,Air Aruba",
# MAGIC "FRA,Freedom Air",
# MAGIC "FRS,Four Star Aviation",
# MAGIC "FRT,Frontier Commuter",
# MAGIC "FRW,Farwest Airlines",
# MAGIC "FS,Serv De Trans Aereos Fuegui",
# MAGIC "FSA,F.S. Air Service",
# MAGIC "FT,Flying Tiger Line Inc.",
# MAGIC "FTI,Southern Airways",
# MAGIC "FVA,Skycraft Inc.",
# MAGIC "FW,Skybus Inc.",
# MAGIC "FWA,Far West Airlines",
# MAGIC "FX,Federal Express Corporation",
# MAGIC "FYB,Flying Boat",
# MAGIC "FYQ,Flying Group Lux S.A.",
# MAGIC "G3,VRG Linhas Aereas S A",
# MAGIC "G3 (1),Aerochago S.A.",
# MAGIC "G4,Allegiant Air",
# MAGIC "G7,GoJet Airlines LLC d/b/a United Express",
# MAGIC "GA,P.T. Garuda Indonesian Arwy",
# MAGIC "GAL,Galena Air Service",
# MAGIC "GAQ,Galaxy Airlines Inc.",
# MAGIC "GAS,General Aviation Inc.",
# MAGIC "GAT,Gulf Air Taxi",
# MAGIC "GAV,Gromer Aviation Inc.",
# MAGIC "GBA,Central States Airline",
# MAGIC "GBQ,G5 Executive Ag",
# MAGIC "GCA,Golden Carriage Aire",
# MAGIC "GCH,Grand Canyon Helicopters",
# MAGIC "GCQ,Glock Aviation GmbH",
# MAGIC "GCQ (1),General Air Cargo",
# MAGIC "GCS,Midway Commuter",
# MAGIC "GD,Transp. Aereos Ejecutivos",
# MAGIC "GDW,Golden West Airlines Inc.",
# MAGIC "GE,Lufthansa Cargo Airlines",
# MAGIC "GF,Gulf Air Company",
# MAGIC "GF (1),Gulf Air Transport Inc.",
# MAGIC "GFC,Gulf Flite Center",
# MAGIC "GFQ,Gulf And Caribbean Cargo",
# MAGIC "GG,Cargo 360, Inc.",
# MAGIC "GG (1),Tropical Airways Inc.",
# MAGIC "GG (2),Grenada Airways Ltd.",
# MAGIC "GH,Ghana Airways Corporation",
# MAGIC "GHA,Green Hills Aviation Ltd.",
# MAGIC "GIQ,Global International Airways Corp.",
# MAGIC "GJ,Eurofly S.p.A",
# MAGIC "GJ (1),Mexicargo",
# MAGIC "GKQ,Laker Airways",
# MAGIC "GL,Miami Air International",
# MAGIC "GLW,Golden West Airlines Co.",
# MAGIC "GM,Air America",
# MAGIC "GMA,Green Mountain Airlines Ltd.",
# MAGIC "GOF,Copper State Airlines",
# MAGIC "GPA,GP Express Airlines",
# MAGIC "GQ,Big Sky Airlines Inc.",
# MAGIC "GR,Gemini Air Cargo Airways",
# MAGIC "GRA,Gorda Aero Service",
# MAGIC "GRD,Grand Canyon Airlines",
# MAGIC "GRO,Isle Royale Seaplane Serv.",
# MAGIC "GS,Air Foyle Limited",
# MAGIC "GSA,Golden Gate Airlines Inc.",
# MAGIC "GSC,GCS Air Service",
# MAGIC "GSL,Golden South Airlines Inc.",
# MAGIC "GSQ,Global Supply System",
# MAGIC "GST,Golden State Airlines",
# MAGIC "GU,Aviateca",
# MAGIC "GUL,Gull Air Inc.",
# MAGIC "GUN,Gunnel Aviation Inc.",
# MAGIC "GV,Grant Aviation",
# MAGIC "GW,SkyGreece Airlines S A",
# MAGIC "GW (1),Central American Airlines",
# MAGIC "GWA,Great Western Aviation",
# MAGIC "GWE,Ross Aviation Inc.",
# MAGIC "GX,Air Ontario Limited",
# MAGIC "GY,Guyana Airways Corporation",
# MAGIC "H2,City Bird",
# MAGIC "H5,Magadan Airlines",
# MAGIC "H6,Hageland Aviation Service",
# MAGIC "HA,Hawaiian Airlines Inc.",
# MAGIC "HAQ,Hapag Lloyd Flug.",
# MAGIC "HAR,Friendship Air Alaska",
# MAGIC "HB,Homer Air",
# MAGIC "HB (1),Air Club International",
# MAGIC "HBQ,Harris Air Services",
# MAGIC "HCQ,Av Atlantic",
# MAGIC "HEL,Helitrans",
# MAGIC "HEP,Hub Express",
# MAGIC "HER,Markair Express",
# MAGIC "HET,Helitac Aviation",
# MAGIC "HEU,Heussler Air Service Corp",
# MAGIC "HFQ,Haiti Air Freight Intl",
# MAGIC "HFS,Hensley Flying Service Inc.",
# MAGIC "HIQ,Business Flights Ltd.",
# MAGIC "HJ,Air Haiti S. A.",
# MAGIC "HK,Time Air Sweden Ab",
# MAGIC "HLQ,Heavylift Cargo Airlines Lt",
# MAGIC "HMZ,Long Island Airlines",
# MAGIC "HNS,Haines Airways",
# MAGIC "HOL,Holiday Airlines Inc.",
# MAGIC "HOQ,Holidair Airways",
# MAGIC "HOR,Iowa Airlines",
# MAGIC "HP,America West Airlines Inc. (Merged with US Airways 9/05. Stopped reporting 10/07.)",
# MAGIC "HPZ,Pacific Coast Airlines",
# MAGIC "HQ,Harmony Airways",
# MAGIC "HQ (1),Business Express",
# MAGIC "HQQ,Harlequin Air Corporation",
# MAGIC "HRA,Trans-National Airlines Haw",
# MAGIC "HRG,Heritage Airlines",
# MAGIC "HRQ,Tar Airlines",
# MAGIC "HRZ,Allegheny Airlines",
# MAGIC "HSV,Harbor Air Service",
# MAGIC "HSZ,Scenic Airlines Inc.",
# MAGIC "HU,Hainan Airlines Company Limited",
# MAGIC "HUB,Skystream Airlines",
# MAGIC "HVQ,Transavia Holland B. V.",
# MAGIC "HWK,Hawking Corporation",
# MAGIC "HX,Hong Kong Airlines Limited",
# MAGIC "HX (1),Guy-America Airways Inc.",
# MAGIC "HY,Uzbekistan Airways",
# MAGIC "HYA,Hyannis Aviation",
# MAGIC "I4,Scott Air LLC dba Island Air Express",
# MAGIC "IA,Iraqi Airways",
# MAGIC "IB,Iberia Air Lines Of Spain",
# MAGIC "ICF,Iowa City Flying Service",
# MAGIC "ICH,Island Air Charters",
# MAGIC "ICQ,Iscargo Hf",
# MAGIC "IDQ,Intl Air Service Co. Ltd.",
# MAGIC "IEX,Island Air Express",
# MAGIC "IG,Airitaly S.P.A.",
# MAGIC "IGA,Global Jet Austria, GmbH",
# MAGIC "III,Idee Industries Inc.",
# MAGIC "IJ,Great Wall Airlines Company Limited",
# MAGIC "IKQ,Tradewinds Airways Ltd.",
# MAGIC "IMP,Imperial Airlines Inc.",
# MAGIC "IN,Aerlinte Eireann Teoranta",
# MAGIC "INA,Inland Empire Airlines Inc.",
# MAGIC "IND,Indiana Airways Inc. (Pa)",
# MAGIC "INQ,Independent Air Inc.",
# MAGIC "IOW,Iowa Airways",
# MAGIC "IPI,Indo-Pacific International",
# MAGIC "IPQ,Aruba Cargo",
# MAGIC "IPS,Island Express",
# MAGIC "IR,Iran National Airlines Corp",
# MAGIC "IRQ,Interstate Airlines Inc.",
# MAGIC "ISL,Island Airlines",
# MAGIC "ITQ,Interamericana De Aviacion",
# MAGIC "IW,Air Liberte Aka Aom Minerve",
# MAGIC "IW (1),Best Airlines Inc.",
# MAGIC "IXQ,Inair",
# MAGIC "J2,Azerbaijan Airlines CJSC",
# MAGIC "J5,Kalinin Aviation LLC d/b/a Alaska Seaplanes",
# MAGIC "J6,Larrys Flying Service",
# MAGIC "J7,Valujet Airlines Inc.",
# MAGIC "JAG,JetAlliance Flugbetriebs d/b/a JAF Airservice",
# MAGIC "JAM,Sunbelt Airlines Inc.",
# MAGIC "JAQ,Jamaica Air Freighters",
# MAGIC "JB,Helijet International Inc.",
# MAGIC "JCM,Air Chico",
# MAGIC "JCQ,Jet Connection Businessflight Ag",
# MAGIC "JCZ,Rocky Mountain Airways Inc.",
# MAGIC "JD,Beijing Capital Airlines",
# MAGIC "JD (1),Japan Air System Co. Ltd.",
# MAGIC "JER,Jer-Don Air",
# MAGIC "JF,L.A.B. Flying Service Inc.",
# MAGIC "JI,Jade Cargo International",
# MAGIC "JI (1),Midway Airlines Inc.",
# MAGIC "JIQ,Jet Fleet Intl. Airlines",
# MAGIC "JJ,Transportes Aeros Meridiona",
# MAGIC "JK,Spanair S.A.",
# MAGIC "JK (1),Sunworld International Airways Inc.",
# MAGIC "JKQ,Express One International Inc.",
# MAGIC "JL,Japan Air Lines Co. Ltd.",
# MAGIC "JM,Air Jamaica Limited",
# MAGIC "JMA,Jim Air Inc.",
# MAGIC "JN,Excel Airways",
# MAGIC "JO,Jalways Co. Ltd.",
# MAGIC "JQ,Jetstar Airways Pty Limited",
# MAGIC "JR,Aero California",
# MAGIC "JTA,Jetaire Airlines Inc.",
# MAGIC "JU,Air Serbia",
# MAGIC "JU (1),Yugoslav Airlines",
# MAGIC "JW,Arrow Air Inc.",
# MAGIC "JX,Southeast Airlines",
# MAGIC "JX (1),Jes Air Ltd.",
# MAGIC "JXQ,Allarco Developments Ltd.",
# MAGIC "JZ,Japan Air Charter Co. Ltd.",
# MAGIC "K2,Paklook Air, Inc d/b/a/ Airlift Alaska d/b/a/ Yute Commuter Service",
# MAGIC "K3,Venture Travel LLC d/b/a Taquan Air Service",
# MAGIC "K5,Seaport Airlines, Inc.",
# MAGIC "K7,Arizona Express",
# MAGIC "K8,Dutch Caribbean Airlines",
# MAGIC "KA,Hong Kong Dragonair",
# MAGIC "KAH,Kenmore Air Harbor",
# MAGIC "KAI,Knight Airlines Inc.",
# MAGIC "KAQ,Kalitta Air LLC",
# MAGIC "KAT,Katmai Air",
# MAGIC "KB,Haiti Air",
# MAGIC "KD,Western Global",
# MAGIC "KE,Korean Air Lines Co. Ltd.",
# MAGIC "KEA,Keene Airways",
# MAGIC "KEE,Key Airlines",
# MAGIC "KET,Ketchikan Air Service",
# MAGIC "KFS,King Flying Service",
# MAGIC "KH,Aloha Air Cargo",
# MAGIC "KI,Time Air Ltd.",
# MAGIC "KIN,Golden Pacific Airlines",
# MAGIC "KKQ,Transmeridian Air Cargo Ltd.",
# MAGIC "KL,Klm Royal Dutch Airlines",
# MAGIC "KLQ,Kalitta Charters II",
# MAGIC "KM,Air Malta",
# MAGIC "KN,Morris Air Corporation",
# MAGIC "KO,Alaska Central Express",
# MAGIC "KOD,Kodiak Airways Inc.",
# MAGIC "KP,Kiwi International",
# MAGIC "KQ,Kenya Airways PLC",
# MAGIC "KR,Kitty Hawk Aircargo",
# MAGIC "KR (1),Kar-Air Oy",
# MAGIC "KS,Peninsula Airways Inc.",
# MAGIC "KTQ,Turks Air Ltd.",
# MAGIC "KU,Kuwait Airways Corp.",
# MAGIC "KV,Sky Regional Airlines Inc.",
# MAGIC "KW,Carnival Air Lines Inc.",
# MAGIC "KWQ,Kelowna Flightcraft Air Cha",
# MAGIC "KWZ,Crown Air",
# MAGIC "KX,Cayman Airways Limited",
# MAGIC "KXZ,Chaparral Airlines Inc.",
# MAGIC "KZ,Nippon Cargo Airlines",
# MAGIC "L2,Lynden Air Cargo Airlines",
# MAGIC "L3,Lynx Aviation d/b/a Frontier Airlines",
# MAGIC "L7,Lan Colombia",
# MAGIC "LA,Lan-Chile Airlines",
# MAGIC "LAA,La Skycab Airline",
# MAGIC "LAH,La Helicopter",
# MAGIC "LAN,Lancer Aviation Inc.",
# MAGIC "LAP,Lapsa",
# MAGIC "LAR,Laredo Air",
# MAGIC "LAS,Lake Union Air Service",
# MAGIC "LAW,Lawrence Aviation",
# MAGIC "LB,Lloyd Aereo Boliviano S. A.",
# MAGIC "LBQ,Millon Air Inc.",
# MAGIC "LC,Varig Logistica S/A",
# MAGIC "LC (1),Lineas Aereas Del Caribe",
# MAGIC "LC (2),Legend Airlines",
# MAGIC "LCQ,Latcr",
# MAGIC "LCT,Lake Coastal",
# MAGIC "LDM,Lauda Motion GmbH",
# MAGIC "LEQ,Le Point Air",
# MAGIC "LEX,L'Express",
# MAGIC "LF,CFM Inc d/b/a Contour Airlines d/b/a One Jet Shuttle",
# MAGIC "LF (1),Jettrain Airlines",
# MAGIC "LG,Luxair",
# MAGIC "LGQ,Lineas Aereas Allegro",
# MAGIC "LH,Lufthansa German Airlines",
# MAGIC "LHA,Havasu Airlines",
# MAGIC "LIQ,Liat (1974) Limited",
# MAGIC "LJ,Jin Air Co Ltd.",
# MAGIC "LKN,Loken Aviation",
# MAGIC "LLA,Lakeland Aviation",
# MAGIC "LNQ,Aerolineas Latinas",
# MAGIC "LO,Polskie Linie Lotnicze",
# MAGIC "LOQ,Lorair Ltd.",
# MAGIC "LOS,Aero Commuter",
# MAGIC "LP,Lan Peru Airlines",
# MAGIC "LP (1),The Hawaii Express Inc.",
# MAGIC "LR,Lacsa",
# MAGIC "LRQ,Air Liberte",
# MAGIC "LS,Jet2.com",
# MAGIC "LSQ,Lineas Aereas Suramerican",
# MAGIC "LSZ,Alaska Island Air Inc.",
# MAGIC "LT,Luftransport-Unternehmen",
# MAGIC "LU,Air Atlantic Dominicana",
# MAGIC "LUQ,Lineas Aereas La-Tur Sa",
# MAGIC "LVA,Las Vegas Airlines",
# MAGIC "LW,Pacific Wings Airlines",
# MAGIC "LX,Swiss International Airlines",
# MAGIC "LXQ,Translux Intl Airlines",
# MAGIC "LY,El Al Israel Airlines Ltd.",
# MAGIC "LZ,Balkan Bulgarian Airlines",
# MAGIC "LZQ,Leisure International Airways Ltd.",
# MAGIC "M3,ABSA-Aerolinhas Brasileiras",
# MAGIC "M6,Amerijet International",
# MAGIC "M7,Aerotransportes Mas De Crga",
# MAGIC "MA,Malev Hungarian Airlines",
# MAGIC "MAA,Maui Airlines",
# MAGIC "MAC,Mackey International Inc.",
# MAGIC "MAE,Mid-Atlantic Exp. Airlines",
# MAGIC "MAG,Magum Airlines",
# MAGIC "MAI,The Maui Commuter",
# MAGIC "MAQ,Millardair Limited",
# MAGIC "MAR,Marshall's Air Inc.",
# MAGIC "MAV,Maverick Airways",
# MAGIC "MAX,Maxair Inc.",
# MAGIC "MB,Samoa Airlines Inc.",
# MAGIC "MC,Transtar Airlines Corp.",
# MAGIC "MCO,Mid Continental Airlines In",
# MAGIC "MDC,Midcontinent Airlines",
# MAGIC "MDU,Metro Airlines",
# MAGIC "ME,Middle East Airlines S.A.L.",
# MAGIC "MEA,Manhattan Express",
# MAGIC "MET,Metroplex Airlines",
# MAGIC "MEX,Metro Express 11",
# MAGIC "MF,Xiamen Airlines Co., Ltd.",
# MAGIC "MG,Champion Air",
# MAGIC "MGQ,Montana Austria Flugetrieb",
# MAGIC "MH,Malaysian Airline System",
# MAGIC "MHK,Mohawk Airlines",
# MAGIC "MHO,Mahalo Air",
# MAGIC "MIN,Minuteman Aviation Inc.",
# MAGIC "MIS,Midstate Airlines Inc.",
# MAGIC "MIY,Midway Aviation Inc.",
# MAGIC "MJ,Lapa-Lineas Aereas Privadas",
# MAGIC "MKQ,Airmark Corporation",
# MAGIC "ML,Aero Costa Rica",
# MAGIC "ML (1),Midway Airlines Inc. (1)",
# MAGIC "MLL,Miller Air Transportersinc",
# MAGIC "MLX,Merlin Express",
# MAGIC "MM,Euro Atlantic Airways",
# MAGIC "MM (1),Sociedad Aeronautica De Med",
# MAGIC "MMH,Ocean Airways Inc.",
# MAGIC "MNA,M & N Aviation",
# MAGIC "MNZ,Cumberland Airlines",
# MAGIC "MOQ,Morningstar Air Express",
# MAGIC "MP,Martinair Holland N.V.",
# MAGIC "MPA,Mid Pacific Airlines Inc.",
# MAGIC "MPC,Mid Pacific Air Corp.",
# MAGIC "MQ,Envoy Air",
# MAGIC "MRC,Marco Island Airways Inc.",
# MAGIC "MRR,Merrimack Aviation Inc.",
# MAGIC "MS,Egyptair",
# MAGIC "MST,Midwest Aviation",
# MAGIC "MT,Thomas Cook Airlines Uk Ltd.",
# MAGIC "MT (1),Flying Colours Airlines Ltd.",
# MAGIC "MTA,Arkansas Traveler Airline",
# MAGIC "MTR,Metroflight Airlines",
# MAGIC "MTV,Mst Aviation",
# MAGIC "MTX,Mountain Air Express",
# MAGIC "MU,China Eastern Airlines",
# MAGIC "MU (1),Mcclain Airlines Inc.",
# MAGIC "MUA,Manu'a Air Transport",
# MAGIC "MUQ,Aerolineas Mundo",
# MAGIC "MVA,Mississippi Valley Airlines",
# MAGIC "MW,Mokulele Flight Services, Inc.",
# MAGIC "MWA,Mountain West Airlines",
# MAGIC "MX,Compania Mexicana De Aviaci",
# MAGIC "MY,MAXjet",
# MAGIC "MYQ,Lineas Aereas Mayas (Lamsa)",
# MAGIC "MZ,P.N. Merpati Nusantara Air.",
# MAGIC "N5,Skagway Air Service",
# MAGIC "N5 (1),Nations Air Express Inc.",
# MAGIC "N6,Aero Continente",
# MAGIC "N7,National Airlines",
# MAGIC "N8,National Air Cargo Group Inc d/ba National Airlines",
# MAGIC "NA,North American Airlines",
# MAGIC "NAC,National Air Commuter Inc.",
# MAGIC "NAP,Npa Inc.",
# MAGIC "NAQ,Nationair",
# MAGIC "NAS,Nasville Eagle",
# MAGIC "NAT,National Air",
# MAGIC "NB,Sterling Cargo",
# MAGIC "NBQ,Sterling Airways A/S",
# MAGIC "NC,Northern Air Cargo Inc.",
# MAGIC "NCA,National Commuter Airlines",
# MAGIC "NCE,Northcoast Executive",
# MAGIC "ND,Intair",
# MAGIC "NEB,New Born Wings Inc.",
# MAGIC "NEC,Nor East Commuter Airlines",
# MAGIC "NEQ,North East Cargo Airlines",
# MAGIC "NER,Northeast Express Regional (1)",
# MAGIC "NET,Nacnet",
# MAGIC "NEV,Nevada Airlines",
# MAGIC "NEW,New England Airlines Inc.",
# MAGIC "NEX,Northeast Express Regional",
# MAGIC "NFA,National Florida Airlines",
# MAGIC "NFQ,North Cariboo Flying Serv.",
# MAGIC "NG,Lauda Air Luftfahrt Ag",
# MAGIC "NGL,Northern Eagle Airways Inc.",
# MAGIC "NH,All Nippon Airways Co.",
# MAGIC "NHA,Newair Flight Inc.",
# MAGIC "NI,Lanica",
# MAGIC "NI (1),American International Airways Inc.",
# MAGIC "NJ,Vanguard Airlines Inc.",
# MAGIC "NJA,N. J. Merrimack Airlines",
# MAGIC "NJE,NetJets Transportes Aereos, S.A.",
# MAGIC "NK,Spirit Air Lines",
# MAGIC "NKQ,Norcanair",
# MAGIC "NLQ,Nolinor Aviation",
# MAGIC "NN,Northward Airlines Ltd.",
# MAGIC "NOQ,Novair Airlines Ab",
# MAGIC "NPA,North Pacific Airlines Inc.",
# MAGIC "NPT,E. J. A. Newport Inc.",
# MAGIC "NQ,Air Japan Co",
# MAGIC "NRN,Northern Airlines Inc.",
# MAGIC "NSQ,North Coast Air Services",
# MAGIC "NTH,Northaire",
# MAGIC "NTQ,National Aviation Consult.",
# MAGIC "NUM,Lake State Airways",
# MAGIC "NUQ,Air Niugini",
# MAGIC "NVQ,Novair International Airways Ltd.",
# MAGIC "NVX,Nevis Express",
# MAGIC "NW,Northwest Airlines Inc.",
# MAGIC "NWQ,N. W. Territorial Airways",
# MAGIC "NWS,Northwest Seaplanes",
# MAGIC "NXQ,North Vancouver Air",
# MAGIC "NY,New York Air Inc.",
# MAGIC "NYH,New York Helicopter Corp.",
# MAGIC "NZ,Air New Zealand",
# MAGIC "O6,Oceanair Linhas Aereas S A",
# MAGIC "OA,Olympic Airways",
# MAGIC "OAK,Harbor Airlines Inc.",
# MAGIC "OB,Oasis International Airlines S.A.",
# MAGIC "OC,Air California Inc.",
# MAGIC "OCR,Ocean Reef Airways Inc.",
# MAGIC "OD,Emerald Airlines Inc.",
# MAGIC "OD (1),Aerocondor",
# MAGIC "OE,Westair Airlines Inc.",
# MAGIC "OF,Air Finland Ltd.",
# MAGIC "OFF,Offshore Logistics",
# MAGIC "OH,PSA Airlines Inc.",
# MAGIC "OH (1),Comair Inc.",
# MAGIC "OHA,Omaha Aviation",
# MAGIC "OHZ,Caribbean Air Services Inc.",
# MAGIC "OI,Prestige Airways",
# MAGIC "OIZ,Corporate Air Inc.",
# MAGIC "OJ,Fly Jamaica Airways Limited",
# MAGIC "OK,Czech Airlines",
# MAGIC "OMH,Omniflight Helicopters",
# MAGIC "OMI,Omniflight Airways",
# MAGIC "OMK,Omak Aviation Airlines",
# MAGIC "OMN,Omni Pacific Airline",
# MAGIC "OMQ,Quassar De Mexico",
# MAGIC "ON,Air Nauru",
# MAGIC "ONQ,Nunasi-Central Airlines Ltd.",
# MAGIC "OO,SkyWest Airlines Inc.",
# MAGIC "OOZ,Sun Aire Lines",
# MAGIC "OP,Flying Boat Inc.",
# MAGIC "OP (1),Air Panama Internacional",
# MAGIC "OPQ,Orion Air",
# MAGIC "OR,TUI Airlines Nederland B.V.",
# MAGIC "ORI,Orion Air Inc.",
# MAGIC "OS,Austrian Airlines",
# MAGIC "OTT,Otter Air",
# MAGIC "OV,Aeromaritime",
# MAGIC "OW,Executive Airlines",
# MAGIC "OWQ,Ontario Worldair Limited",
# MAGIC "OWS,Air Kentucky Air Lines",
# MAGIC "OZ,Asiana Airlines Inc.",
# MAGIC "OZ (1),Ozark Air Lines Inc. (1)",
# MAGIC "OZA,Ozark Air Lines Inc.",
# MAGIC "P3,Cargologicair Limited",
# MAGIC "P9,Pro Air Inc.",
# MAGIC "PA,Florida Coastal Airlines",
# MAGIC "PA (1),Pan American World Airways (1)",
# MAGIC "PA (2),Pan American World Airways",
# MAGIC "PAI,Permian Airways Inc.",
# MAGIC "PAQ,Patriot Airlines Inc.",
# MAGIC "PAT,Panorama Air Tours",
# MAGIC "PBA,Provincetown Boston",
# MAGIC "PBQ,Privatair",
# MAGIC "PCA,Piasa Commuter Airlines",
# MAGIC "PCL,Pacific Cal Air",
# MAGIC "PCQ,Pace Airlines",
# MAGIC "PCR,Pacair",
# MAGIC "PD,Porter Airlines, Inc.",
# MAGIC "PD (1),Pem-Air Limited",
# MAGIC "PDA,Trans Southern Airways",
# MAGIC "PDQ,Antigua Paradise Airways",
# MAGIC "PE,Air Europe S.P.A.",
# MAGIC "PE (1),People Express Airlines Inc.",
# MAGIC "PEA,Pearson Aircraft",
# MAGIC "PEQ,SkyLink Express Inc.",
# MAGIC "PER,Air Pennsylvania",
# MAGIC "PET,Petro Aviation Corp.",
# MAGIC "PF,Primera Air Scandinavia",
# MAGIC "PFA,Pacificair",
# MAGIC "PFQ,Asia Pacific",
# MAGIC "PH,Polynesian Airlines Ltd.",
# MAGIC "PHL,Phillips Airlines",
# MAGIC "PHR,Pinehurst Airlines Inc.",
# MAGIC "PHX,Phoenix Airlines",
# MAGIC "PI,Piedmont Aviation Inc.",
# MAGIC "PIA,Pacific Island Airways",
# MAGIC "PIQ,Pacific International Airlines",
# MAGIC "PK,Pakistan International Airlines",
# MAGIC "PKQ,Skyworld Airlines Inc.",
# MAGIC "PL,Aero Peru",
# MAGIC "PLA,Planes Inc.",
# MAGIC "PLQ,Planet Airways",
# MAGIC "PLZ,Polar Airways Inc.",
# MAGIC "PM,Prescott Support Company, Inc.",
# MAGIC "PMA,Pacific Missionary Aviation",
# MAGIC "PMT,Pilgrim Aviation & Airlines",
# MAGIC "PN,Pan American Airways Corp.",
# MAGIC "PNM,Panama Aviation",
# MAGIC "PNQ,Panagra Airways",
# MAGIC "PNR,Pioneer Airways",
# MAGIC "PNS,Pine State Airlines",
# MAGIC "PO,Polar Air Cargo Airways",
# MAGIC "POA,Potomac Air",
# MAGIC "POC,Pocono Airlines Inc.",
# MAGIC "POL,Polar International",
# MAGIC "POM,Pompano Airways",
# MAGIC "PON,Ponderosa Aviation Inc.",
# MAGIC "POQ,Polyot Airlines",
# MAGIC "PP,Jet Aviation Business Jets AG",
# MAGIC "PPQ,Propair",
# MAGIC "PR,Philippine Airlines Inc.",
# MAGIC "PRA,Princeton Aviation Corp",
# MAGIC "PRD,Paradise Island Airlines",
# MAGIC "PRM,Prime Air Inc.",
# MAGIC "PRN,Puerto Rico Intl Airlines",
# MAGIC "PRO,Sundance Airlines",
# MAGIC "PRP,Propheter Aviation",
# MAGIC "PRQ,Florida West Airlines Inc.",
# MAGIC "PRR,Pro Air Services",
# MAGIC "PS,Ukraine International Airlines",
# MAGIC "PS (1),Pacific Southwest Airlines",
# MAGIC "PSA,P.S. Air Freight Inc.",
# MAGIC "PT,Piedmont Airlines",
# MAGIC "PT (1),Capital Cargo International",
# MAGIC "PTQ,Flight International",
# MAGIC "PU,Primeras Lineas Uruguays For International",
# MAGIC "PUQ,Aeropuma",
# MAGIC "PV,Eastern Provincial Airways",
# MAGIC "PVA,Precision Valley Aviation",
# MAGIC "PW,Pacific Western Airlines",
# MAGIC "PY,Surinam Airways Limited",
# MAGIC "PZ,Lineas Aereas Paraguayas",
# MAGIC "Q2,Zambia Airways Corp.",
# MAGIC "Q4,Master Top Linhas Aereas, Ltda.",
# MAGIC "Q5,40-Mile Air",
# MAGIC "Q7,SkyBahamas Airlines Ltd.",
# MAGIC "Q7 (1),Sobelair",
# MAGIC "QB,Inter-Quebec (Intair)",
# MAGIC "QD,Grand Airways Inc.",
# MAGIC "QF,Qantas Airways Ltd.",
# MAGIC "QG,Sky West Aviation Inc.",
# MAGIC "QH,Air Florida Inc.",
# MAGIC "QK,Jazz Aviation LP",
# MAGIC "QN,Royal Air",
# MAGIC "QO,Aeromexpress",
# MAGIC "QOZ,Bar Harbor Airways",
# MAGIC "QQ,Reno Air Inc.",
# MAGIC "QR,Qatar Airways (Q.C.S.C)",
# MAGIC "QS,Travel Service, a.s. d/b/a SmartWings",
# MAGIC "QS (1),Northeastern International Airways",
# MAGIC "QT,Transportes Aereos Mercantiles Panamericanos S.A",
# MAGIC "QTQ,Aer Turas Teoranta",
# MAGIC "QWE,Qwest Commuter",
# MAGIC "QX,Horizon Air",
# MAGIC "QY,European Air Transport Leipzig GmbH",
# MAGIC "R0,Tantalus Air Ltd. d/b/a Harbour Air d/b/a Harbour Air Seaplanes",
# MAGIC "R2,Orenburg Airlines",
# MAGIC "R3,Air Company Yakutia",
# MAGIC "RAL,Royal-Air Ltd.",
# MAGIC "RAN,Pan Am Express",
# MAGIC "RAQ,Arista International Airlines Inc.",
# MAGIC "RAY,Royale Airlines Inc.",
# MAGIC "RB,Syrian Arab Airlines",
# MAGIC "RC,Republic Airlines Inc.",
# MAGIC "RCA,Mid-South Aviation Inc. (1)",
# MAGIC "RD,Ryan International Airlines",
# MAGIC "RD (1),Airlift International Inc.",
# MAGIC "RDR,Rader Aviation",
# MAGIC "RDW,Redwing Airways",
# MAGIC "REA,Realwest Airlines",
# MAGIC "RED,Aerosun International Airlines Inc.",
# MAGIC "REQ,Renown Aviation",
# MAGIC "RES,Resort Airlines Inc.",
# MAGIC "RG,Varig S. A.",
# MAGIC "RGQ,Regency Air",
# MAGIC "RHA,Royal Hawaiian Airways Inc.",
# MAGIC "RIA,Trump Air",
# MAGIC "RIC,Richardson Aviation",
# MAGIC "RID,Indiana Airways Inc. (Reid",
# MAGIC "RIO,Rio Airways Inc.",
# MAGIC "RIQ,Rich International Airways",
# MAGIC "RIV,Riverside Air Service",
# MAGIC "RJ,Alia-(The) Royal Jordanian",
# MAGIC "RJS,Michigan Airways Inc.",
# MAGIC "RK,Air Afrique",
# MAGIC "RL,UltrAir",
# MAGIC "RL (1),Aerolineas Nicaraguenses",
# MAGIC "RLQ,Reliant Airlines",
# MAGIC "RMH,Rocky Mountain Helicopters",
# MAGIC "RMV,Ram Aviation",
# MAGIC "RNQ,Mytravel Airways",
# MAGIC "RO,Tarom Romanian Air Transpor",
# MAGIC "ROA,Royal West Airways Inc.",
# MAGIC "ROE,Roederer Aviation Inc.",
# MAGIC "ROQ,Aero Uruguay (1)",
# MAGIC "ROS,Great Western Airlines Inc.",
# MAGIC "ROY,Royal American Airways Inc.",
# MAGIC "RP,Chautauqua Airlines Inc.",
# MAGIC "RRT,Air Freight Express",
# MAGIC "RSC,Resort Commuter",
# MAGIC "RSQ,Aerotransportes Entre Rios",
# MAGIC "RSV,Air-Serve",
# MAGIC "RTQ,Aerotour Dominicano Cxa",
# MAGIC "RU,AirBridgeCargo Airlines Limited",
# MAGIC "RV,Air Canada rouge LP",
# MAGIC "RV (1),Reeve Aleutian Airways Inc.",
# MAGIC "RVA,Reeves Air",
# MAGIC "RVQ,Reeve Air Alaska, LLC",
# MAGIC "RWG,Air Rovers Inc.",
# MAGIC "RY,Redcoat Air Cargo Limited",
# MAGIC "RZZ,Aeromech Inc.",
# MAGIC "S3,Santa Barbara Airlines, C.A",
# MAGIC "S4,Sata Internacional",
# MAGIC "S5,Shuttle America Corp.",
# MAGIC "S6,Star Air A/S",
# MAGIC "S6 (1),Mountain Bird/Salmon Air",
# MAGIC "SA,South African Airways",
# MAGIC "SAC,Sundorph Aeronautical Corp.",
# MAGIC "SAH,Sea Air Shuttle",
# MAGIC "SAI,Seair Alaska Airlines Inc.",
# MAGIC "SAJ,Sajen Air Inc.",
# MAGIC "SAL,Sallee's Aviation",
# MAGIC "SAM,Samoan Airlines Inc.",
# MAGIC "SAQ,Southern Air Transport Inc.",
# MAGIC "SAS,Air Cortez International",
# MAGIC "SAX,Air Americana",
# MAGIC "SBA,Saber Aviation Inc.",
# MAGIC "SBN,Suburban Airlines",
# MAGIC "SBQ,Skyjet S.A.",
# MAGIC "SCN,Scott Aviation",
# MAGIC "SCO,Seaco Airlines Inc.",
# MAGIC "SCT,Skyline Airlines",
# MAGIC "SCY,South Coast Airways",
# MAGIC "SDQ,St. Lucia Airways Limited",
# MAGIC "SE,XL Airways France",
# MAGIC "SE (1),Das Air Cargo",
# MAGIC "SEB,Seaborne Virgin Islands, Inc.",
# MAGIC "SEG,Seagull Air Service",
# MAGIC "SEM,Semo Aviation Inc.",
# MAGIC "SEP,Southern Express Airways",
# MAGIC "SEQ,Sky Service F.B.O.",
# MAGIC "SER,Service Aviation Inc.",
# MAGIC "SFI,Stahmannfarms Inc.",
# MAGIC "SFO,Sfo Helicopter Airlines Inc.",
# MAGIC "SFQ,Pacific International Airlines Inc.",
# MAGIC "SFQ (1),Southern Frontier Air Trans",
# MAGIC "SFS,Sierra Flite Service Inc.",
# MAGIC "SG,Jetsgo",
# MAGIC "SH,Servicio Aereo De Honduras",
# MAGIC "SHS,Shasta Air Inc.",
# MAGIC "SHV,Shavano Air Inc.",
# MAGIC "SI,Sierra Pacific Airlines",
# MAGIC "SI (1),Jet America Airlines Inc.",
# MAGIC "SIA,Silver State Airlines",
# MAGIC "SIQ,Premiair",
# MAGIC "SIQ (1),Scanair",
# MAGIC "SJA,San Juan Airlines Inc.",
# MAGIC "SJQ,Skycharter (Malton) Ltd.",
# MAGIC "SK,Scandinavian Airlines Sys.",
# MAGIC "SKI,Sunbird Inc.",
# MAGIC "SKJ,Sky-Jet",
# MAGIC "SKL,Bas Airlines",
# MAGIC "SKM,Scheduled Skyways",
# MAGIC "SKS,Silver Kris Services Ltd.",
# MAGIC "SKT,Skytrain",
# MAGIC "SLO,Slocum Air Inc.",
# MAGIC "SLQ,Sky King Inc.",
# MAGIC "SLR,Salair",
# MAGIC "SLZ,Southeast Airlines Inc.",
# MAGIC "SM,Sunworld International Airlines",
# MAGIC "SMC,Stopher Mechanical Inc.",
# MAGIC "SMO,Samoa Aviation Inc.",
# MAGIC "SMQ,Serv. Aerolineas Mexicanas",
# MAGIC "SN,Brussels Airlines N.V.",
# MAGIC "SN (1),Sabena Belgian World Air.",
# MAGIC "SNA,Aviation Associates",
# MAGIC "SNB,Ccair",
# MAGIC "SNC,Gelco Courier Services Inc.",
# MAGIC "SNE,Shawnee Airlines",
# MAGIC "SNK,Spernak Airways Inc.",
# MAGIC "SNV,Sierra Nevada Airways",
# MAGIC "SO,Swiss World Airways",
# MAGIC "SOA,Mall Airways Inc.",
# MAGIC "SOE,Sky One Express",
# MAGIC "SOL,Soonair Lines Inc.",
# MAGIC "SOP,South Pacific Island Airway",
# MAGIC "SPF,Springfield Air Service",
# MAGIC "SPG,Springdale Air",
# MAGIC "SPH,Spirit Helicopter",
# MAGIC "SPQ,Sun Pacific International",
# MAGIC "SPR,Sportsman Flying Service",
# MAGIC "SQ,Singapore Airlines Ltd.",
# MAGIC "SR,Swissair Transport Co. Ltd.",
# MAGIC "SRA,Star Aviation",
# MAGIC "SRL,Sterling Air Service",
# MAGIC "SS,Corsair International",
# MAGIC "SSA,S. S. Airways Inc.",
# MAGIC "SSP,Southern Seaplane",
# MAGIC "SSQ,Superior Airways Limited",
# MAGIC "SSS,Sierra Express Inc.",
# MAGIC "SST,Seaplane Shuttle Transport",
# MAGIC "ST,Belize Airways Limited",
# MAGIC "STA,State Airlines Inc.",
# MAGIC "STF,Trans East International",
# MAGIC "STG,Sedalia Marshall Boonvl Stg",
# MAGIC "STQ,Skycraft Air Transport Inc.",
# MAGIC "STR,Star Aviation Corporation",
# MAGIC "STW,Stateswest Airlines",
# MAGIC "STZ,Air America Inc.",
# MAGIC "SU,Aeroflot Russian Airlines",
# MAGIC "SUA,Sunshine Airlines",
# MAGIC "SUI,Sun International Airways",
# MAGIC "SUT,Sunbelt",
# MAGIC "SUX,Sunair Express LLC",
# MAGIC "SV,Saudi Arabian Airlines Corp",
# MAGIC "SVL,Sun Valley Airlines",
# MAGIC "SVW,Global Jet Luxembourg, Sa",
# MAGIC "SWA,Sunwest Airlines",
# MAGIC "SWT,Swift Aire Lines Inc.",
# MAGIC "SX,Skybus Airlines, Inc.",
# MAGIC "SX (1),Aeroejecutivo S.A.",
# MAGIC "SXP,Sierra Expressway",
# MAGIC "SY,Sun Country Airlines d/b/a MN Airlines",
# MAGIC "SYB,Skybus Express Airlines",
# MAGIC "SYM,Skymaster",
# MAGIC "SZQ,Aerolineas El Salvador S A",
# MAGIC "T3,Tristar Airlines Inc.",
# MAGIC "T9,TransMeridian Airlines",
# MAGIC "TA,Taca International Airlines",
# MAGIC "TAC,Air Colorado",
# MAGIC "TAF,Tri Air Freight",
# MAGIC "TAL,Tejas Airlines Inc.",
# MAGIC "TAQ,Taquan Air Service",
# MAGIC "TAS,Yosemite Airlines Inc.",
# MAGIC "TAT,Talarik Creek Air Taxi",
# MAGIC "TB,TUI Airlines Belgium N.V. d/b/a Jetairfly",
# MAGIC "TB (1),USAir Shuttle",
# MAGIC "TBQ,Triair Bermuda Flt Operations",
# MAGIC "TCA,Trans Catalina Airlines",
# MAGIC "TCE,Oceanair Line",
# MAGIC "TCI,Trans California Airlines",
# MAGIC "TCL,Trans-Central Airlines Inc.",
# MAGIC "TCO,Trans-Colorado Airlines",
# MAGIC "TCQ,Express.Net Airlines",
# MAGIC "TDQ,Venexcargo",
# MAGIC "TDQ (1),Transcarga",
# MAGIC "TEN,Tennessee Airways Inc.",
# MAGIC "TER,Terre Haute Air Commuter",
# MAGIC "TFQ,Trans International Airlines Inc.",
# MAGIC "TFZ,Tri-State Airlines Inc.",
# MAGIC "TG,Thai Airways International Ltd.",
# MAGIC "TGO,Trans Air Cargo Inc.",
# MAGIC "TGQ,Tranps Aereos Guatemaltecos",
# MAGIC "TH,Transmile Air Service",
# MAGIC "THA,Tropical Helicopter Airways",
# MAGIC "THO,Thorson Aviation",
# MAGIC "THQ,T-Bird Air Inc.",
# MAGIC "TIA,Trans Air Inc.",
# MAGIC "TIE,Trans International Express",
# MAGIC "TIQ,Tyrolean Jet Service",
# MAGIC "TIS,Skyfreight",
# MAGIC "TJ,Jet Charter Service Inc.",
# MAGIC "TK,Turk Hava Yollari A.O.",
# MAGIC "TKQ,Trans-Air-Link Corporation",
# MAGIC "TLQ,Trans-Mediterranean Airways",
# MAGIC "TMA,Trans Mo Airlines",
# MAGIC "TN,Air Tahiti Nui",
# MAGIC "TNQ,Emery Worldwide Airlines",
# MAGIC "TNS,Transtate Aviation",
# MAGIC "TP,Tap-Portuguese Airlines",
# MAGIC "TPQ,Aerial Transit Company",
# MAGIC "TQQ,Taca Peru",
# MAGIC "TR,Scoot Tigerair Pte Ltd d/b/a Scoot",
# MAGIC "TR (1),Transbrasil S.A.",
# MAGIC "TRA,Aeromexico Travel",
# MAGIC "TRI,Great Plains Airlines Inc.",
# MAGIC "TRO,Air Molakai",
# MAGIC "TRP,Trans Pennsylvania Airlines",
# MAGIC "TRQ,Blue Scandinavia Ab",
# MAGIC "TRR,Territorial Airlines",
# MAGIC "TS,Air Transat",
# MAGIC "TSF,American Central Airlines",
# MAGIC "TSI,Trans Sierra Airlines Inc.",
# MAGIC "TSQ,TPI International Airways",
# MAGIC "TTM,The Time Machine",
# MAGIC "TUL,Tulsair Beechcraft Inc.",
# MAGIC "TUR,Turner Aire",
# MAGIC "TV,Haiti Trans Air",
# MAGIC "TV (1),Transamerica Airlines Inc.",
# MAGIC "TVL,Travelair",
# MAGIC "TW,Trans World Airways LLC",
# MAGIC "TWA,Trans Western Airlines Utah",
# MAGIC "TWE,Trans World Express",
# MAGIC "TX,Soc.Nouvelle Air Guadeloupe",
# MAGIC "TX (1),Transportes Aereos Nacional",
# MAGIC "TXA,Texas National Airlines",
# MAGIC "TXE,Trans Air (Hawaii)",
# MAGIC "TXQ,British Caribbean Airways",
# MAGIC "TXY,Texas Airways",
# MAGIC "TYE,Temsco Airlines",
# MAGIC "TZ,ATA Airlines d/b/a ATA",
# MAGIC "TZQ,First Choice Airways",
# MAGIC "U2,UFS Inc.",
# MAGIC "U5,USA 3000 Airlines",
# MAGIC "U7,USA Jet Airlines Inc.",
# MAGIC "UA,United Air Lines Inc.",
# MAGIC "UAI,Universal Airways Inc.",
# MAGIC "UC,Ladeco",
# MAGIC "UD,Fast Air Carrier Ltd.",
# MAGIC "UH,US Helicopter Corporation",
# MAGIC "UMQ,Air Manila Inc.",
# MAGIC "UN,Transaero Airlines",
# MAGIC "UNQ,Overseas National Airways",
# MAGIC "UO,Hong Kong Express Airways Limited",
# MAGIC "UP,Bahamasair Holding Limited",
# MAGIC "UR,Empire Airlines Inc. (1)",
# MAGIC "URQ,Aero Uruguay",
# MAGIC "US,US Airways Inc.",
# MAGIC "USA,Air U.S.",
# MAGIC "UT,Union De Transports Aeriens",
# MAGIC "UTQ,Universal Airlines Inc.",
# MAGIC "UX,Air Europa",
# MAGIC "UX (1),Air Illinois Inc.",
# MAGIC "UYQ,Aerolineas Uruguayas S.A.",
# MAGIC "V4,Vensecar International",
# MAGIC "V5,J.D.Valenciana De Aviation",
# MAGIC "V8,Iliamna Air Taxi",
# MAGIC "V9,Eagle Airlines",
# MAGIC "VA,Virgin Blue International Airlines t/a V Australia",
# MAGIC "VA (1),Venezuelan International Airways",
# MAGIC "VAG,Vagabond Aviation Inc.",
# MAGIC "VAQ,Vacationair",
# MAGIC "VAS,Valley Air Services",
# MAGIC "VB,Aeroenlaces Nacionales, S.A. de C.V. d/b/a VivaAerobus",
# MAGIC "VB (1),Pacific Express",
# MAGIC "VC,Servicios Avensa",
# MAGIC "VCQ,Victory Air Transport Inc.",
# MAGIC "VE,Aerovias Venezolanas-Avensa",
# MAGIC "VER,Britt Airlines Inc.",
# MAGIC "VEZ,Valdez Airlines",
# MAGIC "VH,Aeropostal Alas De Venezuel",
# MAGIC "VI,Vieques Air Link Inc.",
# MAGIC "VIG,Viking Express",
# MAGIC "VIN,Vale International Airlines",
# MAGIC "VIQ,Volga-Dnepr Airlines",
# MAGIC "VIQ (1),Viscount Air Service Inc.",
# MAGIC "VIS,Virgin Islands Seaplane",
# MAGIC "VJT,VistaJet Limited",
# MAGIC "VK,Air Tungaru Corporation",
# MAGIC "VL,Mid-South Aviation Inc.",
# MAGIC "VLA,Village Aviation",
# MAGIC "VLY,Valley Airlines",
# MAGIC "VOQ,Avalon Aviation Ltd.",
# MAGIC "VP,Viacao Aerea Sao Paulo",
# MAGIC "VQ,Vintage Props & Jets Inc.",
# MAGIC "VR,Transportes Aereos De Cabo",
# MAGIC "VS,Virgin Atlantic Airways",
# MAGIC "VSA,VistaJet Luftfahrtunternehmen GmbH",
# MAGIC "VV,Aerosvit Ukranian Airlines",
# MAGIC "VV (1),Challenge Air Transport Inc.",
# MAGIC "VV (2),Challenge Air International Inc.",
# MAGIC "VW,Transportes Aeromar S.A de C.V",
# MAGIC "VX,Virgin America",
# MAGIC "VX (1),Aces Airlines",
# MAGIC "VY,Highland Express Airways",
# MAGIC "W3,Arik Air International",
# MAGIC "W4,Mn Aviation, Inc.",
# MAGIC "W7,Western Pacific Airlines",
# MAGIC "W8,Cargojet Airways Ltd.",
# MAGIC "W9,Eastwind Airlines Inc.",
# MAGIC "WA,Worldwide Airlines Services",
# MAGIC "WA (1),Western Air Lines Inc.",
# MAGIC "WAC,Air East Airlines",
# MAGIC "WAI,Wise Airlines Inc.",
# MAGIC "WAP,Arrow Panama",
# MAGIC "WAQ,Air Charter Systems (Acs)",
# MAGIC "WAR,Waring Air",
# MAGIC "WAW,Westward Airways Inc.",
# MAGIC "WC,Wien Air Alaska Inc.",
# MAGIC "WCA,Walker's International",
# MAGIC "WCI,Mountainwest Airlines",
# MAGIC "WD,Halisa Air",
# MAGIC "WDQ,Wardair Canada Inc.",
# MAGIC "WE,Centurion Cargo Inc.",
# MAGIC "WEB,Southeast Alaska Airlines",
# MAGIC "WEQ,Aero-Services-Corporate",
# MAGIC "WES,Western Star Airlines Inc.",
# MAGIC "WET,Western Charter Inc.",
# MAGIC "WFS,Wheeler Airlines",
# MAGIC "WFT,Westflight Aviation",
# MAGIC "WG,Sunwing Airlines Inc.",
# MAGIC "WGL,Wrangell Air Service",
# MAGIC "WGQ,Gateway Aviation Limited",
# MAGIC "WI,Sky Lease Cargo",
# MAGIC "WIA,Wisc Air",
# MAGIC "WIL,Will's Air",
# MAGIC "WIR,Williams Air Inc.",
# MAGIC "WL,Caribbean Sun Airlines, Inc. d/b/a World Atlantic Airlines",
# MAGIC "WL (1),World Air Network",
# MAGIC "WLH,Welch Aviation",
# MAGIC "WLQ,Worldwide Airlines Inc.",
# MAGIC "WM,Windward Islands Airways",
# MAGIC "WN,Southwest Airlines Co.",
# MAGIC "WNG,Wings Airways",
# MAGIC "WNQ,Winair Inc.",
# MAGIC "WO,World Airways Inc.",
# MAGIC "WP,Island Air Hawaii",
# MAGIC "WR,WestJet Encore Ltd.",
# MAGIC "WRA,Wra Inc.",
# MAGIC "WRD,Ward Air",
# MAGIC "WRT,Wright Airlines Inc.",
# MAGIC "WS,Westjet",
# MAGIC "WS (1),Suncoast Airlines Inc.",
# MAGIC "WSK,AAR Western Skyways",
# MAGIC "WST,Friday Harbor Seaplanes",
# MAGIC "WSU,Mission Air",
# MAGIC "WT,Nigeria Airways Ltd.",
# MAGIC "WTA,Westates Airlines",
# MAGIC "WV,Air Greco, Inc., d/b/a Wings Air",
# MAGIC "WV (1),Air South Inc. (1)",
# MAGIC "WW,WOW Air ehf",
# MAGIC "WWI,Wings West Airlines",
# MAGIC "WWQ,Worldways Canada Ltd.",
# MAGIC "X4,Air Excursions LLC",
# MAGIC "X9,Omni Air International LLC",
# MAGIC "XAA,Aero Union Corp",
# MAGIC "XAB,Air Polynesia d/b/a DHL Cargo",
# MAGIC "XAC,Air Express International Airlines",
# MAGIC "XAE,Amerford Airways Inc.",
# MAGIC "XAF,Astro-Wing Airlines Inc.",
# MAGIC "XAG,Ball Brothers Inc.",
# MAGIC "XAH,Hawaii Pacific Air",
# MAGIC "XAI,Burlington Northern Inc.",
# MAGIC "XAJ,Central American International",
# MAGIC "XAK,Century Airlines Inc.",
# MAGIC "XAM,Cohlmia Aviation",
# MAGIC "XAO,Dallas Flight Center",
# MAGIC "XAQ,Cam Air International Inc.",
# MAGIC "XAR,Jet Way Inc.",
# MAGIC "XAS,Klondike Air Inc.",
# MAGIC "XAT,Michigan Peninsula Airways",
# MAGIC "XAU,Flight Line Inc.",
# MAGIC "XAY,Pat Air",
# MAGIC "XAZ,Purolator Sky Courier Inc.",
# MAGIC "XBC,Jet East Inc.",
# MAGIC "XBF,WTC Airlines",
# MAGIC "XBH,Profit Airlines Inc.",
# MAGIC "XBI,CF Air Freight",
# MAGIC "XBJ,International Air Service",
# MAGIC "XBM,Phh Air Inc.",
# MAGIC "XBP,Circle Airfreight Corp.",
# MAGIC "XBQ,Aeronaves De Puerto Rico",
# MAGIC "XBR,Allstates Air Cargo Inc.",
# MAGIC "XBT,Pacific Alaska Airlines Inc.",
# MAGIC "XBV,Nal Inc.",
# MAGIC "XBX,Icb International Airlines",
# MAGIC "XBZ,Air Natl Aircraft Sal & Ser",
# MAGIC "XC,Air Caribbean (1)",
# MAGIC "XCA,Hawkins And Powers Aviation",
# MAGIC "XDA,Pacific Air Express Inc.",
# MAGIC "XDC,Hemisphere Air Charter",
# MAGIC "XDD,International Parcel Express Inc.",
# MAGIC "XDE,Air Train Inc.",
# MAGIC "XDF,Salair Inc.",
# MAGIC "XDH,Kitty Hawk Air Cargo",
# MAGIC "XE,ExpressJet Airlines Inc. (1)",
# MAGIC "XF,Vladivostok Air",
# MAGIC "XJ,Mesaba Airlines",
# MAGIC "XK,Aerotal",
# MAGIC "XL,Lan Ecuador",
# MAGIC "XP,XTRA Airways",
# MAGIC "XPA,Express Air d/b/a Sunrise",
# MAGIC "XPQ,International Cargo Xpress",
# MAGIC "XV,Presidential Airways Inc.",
# MAGIC "XY,Munz Northern Airlines Inc.",
# MAGIC "XYZ,Airpac Inc.",
# MAGIC "Y2,Globespan Airways Limited d/b/a Flyglobespan",
# MAGIC "Y4,Concesionaria Vuela Compania De Aviacion SA de CV (Volaris)",
# MAGIC "Y7,Flyjet Limited d/b/a Silverjet",
# MAGIC "Y8,Yangtze River Express Airlines Company",
# MAGIC "YB,Trans Continental Airlines",
# MAGIC "YBQ,Yellow Bird Air",
# MAGIC "YM,Royal West Airlines",
# MAGIC "YR,Grand Canyon Airlines, Inc. d/b/a Grand Canyon Airlines d/b/a Scenic Airlines",
# MAGIC "YV,Mesa Airlines Inc.",
# MAGIC "YX,Republic Airways",
# MAGIC "YX (1),Midwest Airline, Inc.",
# MAGIC "Z3,Bidzy Ta Hot Aana, Inc. d/b/a Tanana Air Service",
# MAGIC "Z3 (1),Promech",
# MAGIC "Z3Q,PM Air, LLC",
# MAGIC "ZA,Accessair Holdings",
# MAGIC "ZAQ,Zas Airline Of Egypt",
# MAGIC "ZB,Monarch Airlines",
# MAGIC "ZE,Eastar Jet Co Ltd.",
# MAGIC "ZE (1),Lineas Aereas Azteca",
# MAGIC "ZFZ,Mcphillips Flying Service",
# MAGIC "ZIA,Air New Mexico",
# MAGIC "ZK,Great Lakes Airlines",
# MAGIC "ZKQ,Zantop International",
# MAGIC "ZL,Affretair",
# MAGIC "ZMZ,Winnipesaukee Aviation Inc.",
# MAGIC "ZN,Key Airlines Inc.",
# MAGIC "ZO,Florida Express Inc.",
# MAGIC "ZP,Air St. Thomas",
# MAGIC "ZS,Hispaniola Airways",
# MAGIC "ZUQ,Zuliana De Aviacion",
# MAGIC "ZV,Air Midwest Inc.",
# MAGIC "ZW,Air Wisconsin Airlines Corp",
# MAGIC "ZX,Air Georgian",
# MAGIC "ZX (1),Airbc Ltd.",
# MAGIC "ZY,Atlantic Gulf Airlines",
# MAGIC "ZYZ,Skyway Aviation Inc.",
# MAGIC   )
# MAGIC )
# MAGIC 
# MAGIC //programmatically defining the schema
# MAGIC val schemaString = "UniqueCode Description"
# MAGIC val schema = StructType(
# MAGIC   schemaString
# MAGIC     .split(" ")
# MAGIC     .map(fieldName ⇒ StructField(fieldName, StringType, true))
# MAGIC )
# MAGIC val rowRDD = lookupCodes.map(_.split(",")).map(e ⇒ Row(e(0).trim, e(1)))
# MAGIC val codesDf = sqlContext.createDataFrame(rowRDD, schema)
# MAGIC 
# MAGIC //creating temp view for SQL queries
# MAGIC codesDf.createOrReplaceTempView("lookupCodes")

# COMMAND ----------

# DBTITLE 1,Create Airline Code Data for Dimensional Airline Carrier Table to Demonstrate Internal & Externally Provided Data Join
# MAGIC %python
# MAGIC airportsnaFilePath = "/databricks-datasets/flights/airport-codes-na.txt"
# MAGIC 
# MAGIC # Obtain airports dataset
# MAGIC airportsna = sqlContext.read.format("com.databricks.spark.csv").options(header='true', inferschema='true', delimiter='\t').load(airportsnaFilePath)
# MAGIC airportsna.createOrReplaceTempView("airports")

# COMMAND ----------

# DBTITLE 1,Create and Register Airline Flights Fact Table Partitioned by Year & Carrier
# MAGIC %sql
# MAGIC USE CATALOG deltasharing;
# MAGIC CREATE OR REPLACE TABLE airlinedata.flights USING DELTA PARTITIONED BY (Year,UniqueCarrier) AS
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   airlineDataTemp2;

# COMMAND ----------

# DBTITLE 1,Create and Register Look-Up Dimensional Code Data 
# MAGIC %sql
# MAGIC USE CATALOG deltasharing;
# MAGIC CREATE OR REPLACE TABLE airlinedata.lookupcodes USING DELTA AS
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   lookupCodes;

# COMMAND ----------

# DBTITLE 1,Create and Register Airports Table for Internal Data Join Example
# MAGIC %sql
# MAGIC USE CATALOG hive_metastore;
# MAGIC CREATE OR REPLACE TABLE default.airports USING DELTA AS
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM
# MAGIC   airports;

# COMMAND ----------

# DBTITLE 1,Optimize Flights Table
# MAGIC %sql
# MAGIC USE CATALOG deltasharing;
# MAGIC OPTIMIZE airlinedata.flights

# COMMAND ----------

# DBTITLE 1,Optimize Lookup Codes Table
# MAGIC %sql
# MAGIC USE CATALOG deltasharing;
# MAGIC OPTIMIZE airlinedata.lookupcodes

# COMMAND ----------

# DBTITLE 1,Optimize Airports Table
# MAGIC %sql
# MAGIC USE CATALOG hive_metastore;
# MAGIC OPTIMIZE default.airports
